export const AVATAR_OPTIONS = [
  {
    id: 'fox',
    emoji: '🦊',
    labelEn: 'Smart Fox',
    labelBn: 'চালাক শিয়াল',
    traitEn: 'Strategic & Clever',
    traitBn: 'কৌশলী ও বুদ্ধিমান',
    bg: 'linear-gradient(135deg, #FF6B4A 0%, #FFA07A 100%)',
    accentColor: '#FF6B4A',
    shadowColor: 'rgba(255, 107, 74, 0.35)',
  },
  {
    id: 'lion',
    emoji: '🦁',
    labelEn: 'Bold Lion',
    labelBn: 'সাহসী সিংহ',
    traitEn: 'Decisive & Confident',
    traitBn: 'সাহসী ও আত্মবিশ্বাসী',
    bg: 'linear-gradient(135deg, #F59E0B 0%, #FBBF24 100%)',
    accentColor: '#F59E0B',
    shadowColor: 'rgba(245, 158, 11, 0.35)',
  },
  {
    id: 'panda',
    emoji: '🐼',
    labelEn: 'Zen Panda',
    labelBn: 'শান্ত পান্ডা',
    traitEn: 'Calm & Balanced',
    traitBn: 'শান্ত ও ভারসাম্যপূর্ণ',
    bg: 'linear-gradient(135deg, #374151 0%, #6B7280 100%)',
    accentColor: '#6B7280',
    shadowColor: 'rgba(107, 114, 128, 0.35)',
  },
  {
    id: 'tiger',
    emoji: '🐯',
    labelEn: 'Fierce Tiger',
    labelBn: 'দুরন্ত বাঘ',
    traitEn: 'Focused & Relentless',
    traitBn: 'লক্ষ্যে অবিচল',
    bg: 'linear-gradient(135deg, #EA580C 0%, #FB923C 100%)',
    accentColor: '#EA580C',
    shadowColor: 'rgba(234, 88, 12, 0.35)',
  },
  {
    id: 'owl',
    emoji: '🦉',
    labelEn: 'Wise Owl',
    labelBn: 'বিজ্ঞ পেঁচা',
    traitEn: 'Knowledge & Analytical',
    traitBn: 'বিজ্ঞ ও দূরদর্শী',
    bg: 'linear-gradient(135deg, #7C3AED 0%, #A78BFA 100%)',
    accentColor: '#7C3AED',
    shadowColor: 'rgba(124, 58, 237, 0.35)',
  },
  {
    id: 'eagle',
    emoji: '🦅',
    labelEn: 'Vision Eagle',
    labelBn: 'তীক্ষ্ণ ঈগল',
    traitEn: 'High-Level Big Picture',
    traitBn: 'দীর্ঘমেয়াদী দূরদৃষ্টি',
    bg: 'linear-gradient(135deg, #1E40AF 0%, #60A5FA 100%)',
    accentColor: '#2563EB',
    shadowColor: 'rgba(37, 99, 235, 0.35)',
  },
  {
    id: 'rocket',
    emoji: '🚀',
    labelEn: 'Growth Rocket',
    labelBn: 'গ্রোথ রকেট',
    traitEn: 'Ambitious & Scaling',
    traitBn: 'দ্রুত প্রবৃদ্ধি অর্জনকারী',
    bg: 'linear-gradient(135deg, #16A34A 0%, #4ADE80 100%)',
    accentColor: '#5ED21C',
    shadowColor: 'rgba(94, 210, 28, 0.4)',
  },
  {
    id: 'lightning',
    emoji: '⚡',
    labelEn: 'Fast Action',
    labelBn: 'তড়িৎ গতি',
    traitEn: 'Agile & Execution-First',
    traitBn: 'তৎক্ষণাৎ সিদ্ধান্ত ও গতি',
    bg: 'linear-gradient(135deg, #D97706 0%, #FDE047 100%)',
    accentColor: '#F59E0B',
    shadowColor: 'rgba(245, 158, 11, 0.35)',
  },
  {
    id: 'diamond',
    emoji: '💎',
    labelEn: 'Wealth Gem',
    labelBn: 'মূল্যবান হীরা',
    traitEn: 'Net Worth Builder',
    traitBn: 'সম্পদ বৃদ্ধি ও সঞ্চয়কারী',
    bg: 'linear-gradient(135deg, #0284C7 0%, #38BDF8 100%)',
    accentColor: '#0EA5E9',
    shadowColor: 'rgba(14, 165, 233, 0.35)',
  },
  {
    id: 'crown',
    emoji: '👑',
    labelEn: 'Finance King',
    labelBn: 'ফাইন্যান্স কিং',
    traitEn: 'Master of Budgeting',
    traitBn: 'বাজেট ও খরচের অধিপতি',
    bg: 'linear-gradient(135deg, #B45309 0%, #FBBF24 100%)',
    accentColor: '#D97706',
    shadowColor: 'rgba(217, 119, 6, 0.35)',
  },
  {
    id: 'sprout',
    emoji: '🌱',
    labelEn: 'Eco Saver',
    labelBn: 'ইকো সেভার',
    traitEn: 'Mindful & Sustainable',
    traitBn: 'মিতব্যয়ী ও দূরদর্শী সঞ্চয়',
    bg: 'linear-gradient(135deg, #15803D 0%, #86EFAC 100%)',
    accentColor: '#16A34A',
    shadowColor: 'rgba(22, 163, 74, 0.35)',
  },
  {
    id: 'target',
    emoji: '🎯',
    labelEn: 'Goal Crusher',
    labelBn: 'গোল ট্র্যাকার',
    traitEn: 'Disciplined Achiever',
    traitBn: 'নির্দিষ্ট লক্ষ্য অর্জনকারী',
    bg: 'linear-gradient(135deg, #DC2626 0%, #FCA5A5 100%)',
    accentColor: '#DC2626',
    shadowColor: 'rgba(220, 38, 38, 0.35)',
  },
];

export function getAvatarConfig(avatarId) {
  if (!avatarId) return null;
  return AVATAR_OPTIONS.find((a) => a.id === avatarId || a.emoji === avatarId) || null;
}
